Andrii/fix/chat auth new design
Simple2B/fan-tickets pull request #22
Opened 2023-12-26 14:51 UTC by AndreyBerezyanskiy

2023-12-26 15:37 UTC, nixissmtp requested changes

2023-12-26 15:37 UTC, nixissmtp commented on app/controllers/chat_auth.py
> +    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
use sa.select(m.User) instead of m.User.select

2023-12-26 15:37 UTC, nixissmtp commented on app/controllers/chat_auth.py
> +    response = c.image_upload(user, c.ImageType.IDENTIFICATION)
why ImageType in CamelCase?

2023-12-26 15:59 UTC, AndreyBerezyanskiy commented on app/controllers/chat_auth.py
> +    response = c.image_upload(user, c.ImageType.IDENTIFICATION)
Because it's Enum. 
` class ImageType(Enum):
    LOGO = "logo"
    IDENTIFICATION = "identification"`

2023-12-27 09:18 UTC, nixissmtp approved these changes

2023-12-27 09:26 UTC, merged