Denys/feature/image upload
Simple2B/fan-tickets pull request #3
Opened 2023-11-21 14:15 UTC by DenisBurimov

2023-11-21 17:51 UTC, kipod requested changes
Good work.
Please work on my comments

2023-11-21 17:51 UTC, kipod commented on app/views/users.py
> +    user_query = m.User.select().where(m.User.unique_id == current_user.unique_id)
```python
user = current_user

2023-11-21 17:51 UTC, kipod commented on app/views/users.py
> +    return {"upload logo status": "ok"}, 200
```python
@bp.route("/logo-upload", methods=["GET", "POST"])
@login_required
def logo_upload():
    image_upload(current_user)
    return {}, 200

2023-11-21 17:51 UTC, kipod commented on app/views/users.py
> +def edit_email():
login_required
and same as function before

2023-11-21 17:51 UTC, kipod commented on app/views/users.py
> +def save_email():
login_required
and same as function before

2023-11-21 17:51 UTC, kipod commented on app/views/users.py
> +def edit_phone():
login_required
and same as function before

2023-11-21 17:51 UTC, kipod commented on app/views/users.py
> +def save_phone():
same

2023-11-21 17:51 UTC, kipod commented on test_flask/conftest.py
> +            "DEBUG": True,
a you really need it?

2023-11-21 17:51 UTC, kipod commented on test_flask/db/__init__.py
> +    folder_path = "test_flask/locations_pictures"  # replace with your folder path
folder_path -> FOLDER_PATH
this is constant

2023-11-21 17:51 UTC, kipod commented on test_flask/test_admin.py
> +from werkzeug.datastructures import FileStorage
format imports

2023-11-22 09:46 UTC, DenisBurimov commented on app/controllers/image_upload.py
> +                mimetype=file.content_type,
Removed

2023-11-22 09:55 UTC, DenisBurimov commented on app/controllers/image_upload.py
> +    if request.method == "POST":
Done

2023-11-22 09:56 UTC, DenisBurimov commented on app/controllers/image_upload.py
> +def image_upload(user: m.User):
Done

2023-11-22 09:58 UTC, DenisBurimov commented on app/controllers/image_upload.py
> +            return redirect(url_for("main.index"))
Fixed. Now it is a completely controllers logic, that is used to save images

2023-11-22 10:00 UTC, DenisBurimov commented on app/models/location.py
> +    )
Thanks for the idea

2023-11-22 10:03 UTC, DenisBurimov commented on app/models/payment.py
> +    )
DONE

2023-11-22 10:05 UTC, DenisBurimov commented on app/models/payment.py
> +    )
Good point. Done

2023-11-22 10:09 UTC, DenisBurimov commented on app/models/payment.py
> +        sa.String(255),
Done

2023-11-22 10:18 UTC, DenisBurimov commented on app/models/user.py
> +    )
Done

2023-11-22 10:34 UTC, DenisBurimov commented on test_flask/test_admin.py
> +from werkzeug.datastructures import FileStorage
Done

2023-11-22 10:39 UTC, DenisBurimov commented on app/templates/user/email_edit.html
> +</form>
Autoformatting removes it in html

2023-11-22 10:48 UTC, DenisBurimov commented on app/templates/user/profile.html
>  {% endblock %}
Prettier removes EOLs

2023-11-22 10:48 UTC, DenisBurimov commented on app/templates/user/phone_edit.html
> +</form>
Prettier removes them

2023-11-22 12:11 UTC, DenisBurimov commented on app/controllers/jinja_globals.py
> +        return None
Removed this global function to use property that returns base64 source

2023-11-22 12:40 UTC, merged